### ISSUE TITLE
MQTT Monitoring setup

### ISSUE THREAD

**Issue by WirthmU** [markmac99/ukmon-pitools#93]
I did attempt to install according to the setup directions (client version on the pi - the MQTT broker server is already running elswhere): https://github.com/markmac99/ukmon-pitools/wiki/Monitoring_with_MQTT

Installation went smoothly but upon testing I get the following error:

```
(vRMS) pi@raspberrypi:~/source/rms_mqtt $ python3 sendToMQTT.py test
Traceback (most recent call last):
  File "sendToMQTT.py", line 152, in <module>
    test_mqtt()
  File "sendToMQTT.py", line 138, in test_mqtt
    client = mqtt.Client(hname)
  File "/home/pi/vRMS/lib/python3.7/site-packages/paho/mqtt/client.py", line 767, in __init__
    "Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details"
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
```
Any help to this?

**Comment by WirthmU** [comment]
Could you please delete this - I copied it to the respective repository.

**Comment by ukmda** [comment]
Do you mean that you've solved the issue?

**Comment by ukmda** [comment]
oh I see what you mean, you've raised the issue in the correct repo. You can just close this issue then !
